'use strict'

angular.module('weganga', ['ngCookies', 'ngSanitize', 'ngResource', 'angular-loading-bar','ngAnimate', 'ui.router', 'ui.bootstrap', 'pascalprecht.translate', 'weganga.admin', 'weganga.user', 'weganga.controllers', 'weganga.directives', 'weganga.filters', 'weganga.services']);

angular.module('weganga').config(['$translateProvider', '$httpProvider', function ($translateProvider, $httpProvider) {
    $translateProvider.translations('en', {
        TITLE: 'The Online Shop',
        SUBTITLE: 'A place to buy and shop',
        COMMENTS: 'Comments',
        BY: 'By',
        ADD: 'Add',
        WISHLIST: 'Wish List',
        LOGIN: 'Login',
        LOGOUT: 'Logout',
        MANAGE: 'Manage',
        REGISTER: 'Register',
        ORDERHISTORY: 'Order history',
        INVITE: 'Invite and win',
        ABOUT: 'About',
        HOME: 'Home',
        DAILYDEALS: 'Daily Deals',
        DOMESTICAPPLIANCES: 'Domestic Appliances',
        ELECTRONICSUPLIES: 'Electronic Suplies',
        HOMESWEETHOME: 'Home, Sweet Home',
        ACCESSORIES: 'Accessories',
        OUTLET: 'Outlet',
        ABOUTUS: 'About Us',
        ABOUTUSPARRAFO: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.',
        ABOUTUSPARRAFOPAGE: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.',
        HELP: 'Help',
        FAQEXTENDED: 'Frecuently Asked Questions',
        CONTACT: 'Contact',
        SHIPPING: 'Shipping',
        TERMS: 'Terms & Conditions',
        MYACCOUNT: 'My Account',
        DESIGNBY: 'Design By ',
        OURJOURNEY: 'Our Journey',
        FECHA1: 'May 2015',
        PARRAFO1: '',
        FECHA2: 'September 2015',
        PARRAFO2: '',
        FECHA3: 'April 2016',
        PARRAFO3: '',
        FECHA4: 'November 2016',
        PARRAFO4: '',
        OURADVANTAGES: 'Our Advantages',
        VENTAJA1: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA1: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        VENTAJA2: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA2: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        VENTAJA3: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA3: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        OURSKILLS: 'Our Skills',
        OURSKILLSTEXT: 'Donec sagittis interdum tellus sed bibendum. Aen ean fringilla ut lacus eu vehicula. Curabitur non nibh quis nisi vestibulum aliquet non sed dolor. Ut est risus, consectetur sit amet pretium in, cursus in dui. Donec ac rhoncus libero.',
        SKILL1: 'Praesent vestibulum molestie lacus',
        SKILL2: 'Donec sagittis interdum tellus',
        SKILL3: 'Nulla consectetur adipiscing',
        SKILL4: 'Donec ac rhoncus libero.',
        SKILL5: 'Erci eu tincidunt lacinia',
        OFFERS: 'Offers',
        CONTACTINFORMATION: 'Contact Information',
        VER: 'See',
        NAME: 'Name',
        EMAIL: 'Email',
        MESSAGE: 'Message',
        SUBMIT: 'Submit',
        FAQ1: 'Question number 1',
        FAQ1TEXT: 'Answer to question 1',
        FAQ2: 'Question number 2',
        FAQ2TEXT: 'Answer to question 2',
        FAQ3: 'Question number 3',
        FAQ3TEXT: 'Answer to question 3',
        FAQ4: 'Question number 4',
        FAQ4TEXT: 'Answer to question 4',
        FAQ5: 'Question number 5',
        FAQ5TEXT: 'Answer to question 5',
        FAQ6: 'Question number 6',
        FAQ6TEXT: 'Answer to question 6',
        AGREGARSEALACOMPRA: 'Add me to the purchase',
        AGREGARALISTADEDESEO: 'Add to my wish list',
        LUGAR: 'Place',
        DESCRIPCION: 'Description',
        CONDITIONS: 'Conditions',
        CATEGORIAS: 'Categorys',
        MOREINFO: 'Additional Info',
        BUSCATUOFERTA: 'Search your offer here',
        PRODUCTO: 'Product',
        COST: 'Cost',
        CANTIDAD: 'Quantity',
        FECHA: 'Date',
        OFFER: 'Offer',
        VENDEDOR: 'Provider',
        APUNTARSE: 'Add me',
        YEAR: 'Year',
        MONTH: 'Month',
        DAY: 'Day',
        CAMPOOBLIGATORIO: 'This field is mandatory',
        ESCOJACATEGORIA: 'Select categorys',
        LIMITOVER: 'You have exceeded the character limit',
        DE: 'From',
        A: 'To',
        TEXTOAFILTRAR: 'Text to filter',
        FILTRAR: 'Filter',
        IMPORTE: 'Amount',
        VISITARSITIO: 'Visit site',
        INFORMES: 'Reports',
        USUARIOS: 'Users',
        VENDEDORES: 'Providers',
        VENTAS: 'Sales',
        IMPUESTOS: 'Taxes',
        REGLASPROMOCION: 'Promotion rules',
        REGLASCARRITO: 'Shop car rules',
        FORGOTPASSWORD: 'Forgot password',
        INVALIDUSERNAME: 'Invalid Username/Password',
        USERNAME: 'Username',
        LASTNAME: 'Last Name',
        PASSWORD: 'Password',
        SINCUENTA: 'Do not have an account',
        INVALIDDATA: 'Invalid Data',
        PASSWORDNOEQUALS: 'Passwords do not match',
        REPEATEDPASSWORD: 'Retype password',
        YATIENECUENTA: 'Already register',
        PEDIDOS: 'Requests',
        BULKLOAD: 'Bulk Load',
        AGREGAR: 'Add',
        DESCUENTO: 'Discount',
        COMPRADORES: 'Buyers',
        ELIMINAR: 'Delete',
        EDITAR: 'Edit',
        TELEFONO: 'Phone',
        DIRECCION: 'Address',
        ROL: 'Role',
        PERSONALDETAILS: 'Personal Details',
        ACCOUNTDETAILS: 'Account Details',
        CODIGOPOSTAL: 'Postal code',
        ESCOJAROL: 'Select a role',
        CLIENTE: 'Client',
        ADMINISTRADOR: 'Administrator',
        ESTADO: 'State',
        ESCOJAPROVEEDOR: 'Select the provider',
        BUSCAR: 'Search',
        ESCOJAUSUARIO: 'Select the user',
        ESCOJAOFERTA: 'Select the offer',
        TASA: 'Rate',
    });

    $translateProvider.translations('es', {
        TITLE: 'la tienda online',
        SUBTITLE: 'Un lugar para vender y comprar',
        COMMENTS: 'Comentarios',
        BY: 'Por',
        ADD: 'Agregar',
        WISHLIST: 'Lista de deseos',
        LOGIN: 'Entrar',
        LOGOUT: 'Salir',
        MANAGE: 'Administrar',
        REGISTER: 'Registrarse',
        ORDERHISTORY: 'Historial de pedidos',
        INVITE: 'Invita y gana',
        ABOUT: 'Acerca de',
        HOME: 'Inicio',
        DAILYDEALS: 'Ofertas del dia',
        DOMESTICAPPLIANCES: 'Usos domesticos',
        ELECTRONICSUPLIES: 'Suministros electronicos',
        HOMESWEETHOME: 'Hogar, dulce hogar',
        ACCESSORIES: 'Accesorios',
        OUTLET: 'Exterior',
        ABOUTUS: 'Sobre nosotros',
        ABOUTUSPARRAFO: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.',
        ABOUTUSPARRAFOPAGE: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.',
        HELP: 'Ayuda',
        FAQEXTENDED: 'Preguntas frecuentes',
        CONTACT: 'Contacta',
        SHIPPING: 'Envio',
        TERMS: 'Terminos & condiciones',
        MYACCOUNT: 'Mi cuenta',
        DESIGNBY: 'Diseñado por ',
        OURJOURNEY: 'Nuestro recorrido',
        FECHA1: 'Mayo del 2015',
        PARRAFO1: '',
        FECHA2: 'Septiembre del 2015',
        PARRAFO2: '',
        FECHA3: 'Abril del 2016',
        PARRAFO3: '',
        FECHA4: 'Noviembre del 2016',
        PARRAFO4: '',
        OURADVANTAGES: 'Nuestras ventajas',
        VENTAJA1: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA1: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        VENTAJA2: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA2: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        VENTAJA3: 'asd askdnas daksd kas',
        DESCRIPCIONVENTAJA3: 'kjnasd kasdhkasdh kasd das dasdhkjhasdkas hdkuhas kdhas kudhasudka',
        OURSKILLS: 'Nuestras habilidades',
        OURSKILLSTEXT: 'Donec sagittis interdum tellus sed bibendum. Aen ean fringilla ut lacus eu vehicula. Curabitur non nibh quis nisi vestibulum aliquet non sed dolor. Ut est risus, consectetur sit amet pretium in, cursus in dui. Donec ac rhoncus libero.',
        SKILL1: 'Praesent vestibulum molestie lacus',
        SKILL2: 'Donec sagittis interdum tellus',
        SKILL3: 'Nulla consectetur adipiscing',
        SKILL4: 'Donec ac rhoncus libero.',
        SKILL5: 'Erci eu tincidunt lacinia',
        OFFERS: 'Ofertas',
        CONTACTINFORMATION: 'Informacion de contacto',
        VER: 'Ver',
        NAME: 'Nombre',
        EMAIL: 'Email',
        MESSAGE: 'Mensage',
        SUBMIT: 'Enviar',
        FAQ1: 'pregunta numeero 1',
        FAQ1TEXT: 'respuesta a la pregunta 1',
        FAQ2: 'pregunta numeero 2',
        FAQ2TEXT: 'respuesta a la pregunta 2',
        FAQ3: 'pregunta numeero 3',
        FAQ3TEXT: 'respuesta a la pregunta 3',
        FAQ4: 'pregunta numeero 4',
        FAQ4TEXT: 'respuesta a la pregunta 4',
        FAQ5: 'pregunta numeero 5',
        FAQ5TEXT: 'respuesta a la pregunta 5',
        FAQ6: 'pregunta numeero 5',
        FAQ6TEXT: 'respuesta a la pregunta 6',
        AGREGARSEALACOMPRA: 'Agregarse a la compra',
        AGREGARALISTADEDESEO: 'Agregar a la lista de deseo',
        LUGAR: 'Lugar',
        DESCRIPCION: 'Descripcion',
        CONDITIONS: 'Condiciones',
        CATEGORIAS: 'Categorias',
        MOREINFO: 'Informacion adicional',
        BUSCATUOFERTA: 'Busca tu oferta aqui',
        PRODUCTO: 'Producto',
        COST: 'Precio',
        CANTIDAD: 'Cantidad',
        FECHA: 'Fecha',
        OFFER: 'Oferta',
        VENDEDOR: 'Proveedor',
        APUNTARSE: 'Apuntarse',
        YEAR: 'Año',
        MONTH: 'Mes',
        DAY: 'Dia',
        CAMPOOBLIGATORIO: 'Este campo es obligatorio',
        ESCOJACATEGORIA: 'Seleccione las categorias',
        LIMITOVER: 'Ha sobrepasado el limite de caracteres',
        DE: 'De',
        A: 'A',
        TEXTOAFILTRAR: 'Texto a filtar',
        FILTRAR: 'Filtrar',
        IMPORTE: 'Importe',
        VISITARSITIO: 'Visitar sitio',
        INFORMES: 'Reportes',
        USUARIOS: 'Usuarios',
        VENDEDORES: 'Proveedores',
        VENTAS: 'Ventas',
        IMPUESTOS: 'Impuestos',
        REGLASPROMOCION: 'Reglas de promocion',
        REGLASCARRITO: 'Reglas del carrito',
        FORGOTPASSWORD: 'Olvido su contraseña',
        INVALIDUSERNAME: 'Nombre de usuario/contraseña invalidos',
        USERNAME: 'nombre de usuario',
        LASTNAME: 'Apellidos',
        PASSWORD: 'Contraseña',
        SINCUENTA: 'No tiene cuenta',
        INVALIDDATA: 'Datos invalidos',
        PASSWORDNOEQUALS: 'Las contraseñas no son iguales',
        REPEATEDPASSWORD: 'Repita la  contraseña',
        YATIENECUENTA: 'Ya tiene cuenta',
        PEDIDOS: 'Pedidos',
        BULKLOAD: 'Carga masiva',
        AGREGAR: 'Agregar',
        DESCUENTO: 'Descuento',
        COMPRADORES: 'Compradores',
        ELIMINAR: 'Eliminar',
        EDITAR: 'Editar',
        TELEFONO: 'Telefono',
        DIRECCION: 'Direccion',
        ROL: 'Rol',
        PERSONALDETAILS: 'Datos personales',
        ACCOUNTDETAILS: 'Account Details',
        CODIGOPOSTAL: 'Codigo postal',
        ESCOJAROL: 'Escoja el rol',
        CLIENTE: 'Client',
        ADMINISTRADOR: 'Administrator',
        ESTADO: 'Estado',
        ESCOJAUSUARIO: 'Seleccione el usuario',
        ESCOJAPROVEEDOR: 'Seleccione el proveedor',
        ESCOJAOFERTA: 'Seleccione la oferta',
        BUSCAR: 'Buscar',
        TASA: 'Tasa',
    });

    $translateProvider.preferredLanguage('en');

    $httpProvider.defaults.withCredentials = false;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
    $httpProvider.defaults.headers.common = {};
    $httpProvider.defaults.headers.post = {};
    $httpProvider.defaults.headers.delete = {};
    $httpProvider.defaults.headers.put = {};

}]);

angular.module('weganga').run(['$state', '$rootScope', '$translate', function ($state, $rootScope, $translate) {

    $state.go('user.ofertas');

    $rootScope.languagePreference = {currentLanguage: 'en'};

    $rootScope.languagePreference.switchLanguage = function (key) {
        $translate.use(key);
        $rootScope.languagePreference.currentLanguage = key;
    }
}]);
